config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :sessions, only: [:new, :create]
  get 'login', controller: :sessions, action: :new
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'maintenance', to: 'sessions#maintenance', as: :maintenance

  resources :reset_passwords, except: [:index, :destroy, :show]
  get 'reset_password', controller: :reset_passwords, action: :new, as: :new_password

  resources :registrations, only: [:new, :create] do
    member do
      get 'activate'
    end
  end

  get 'dashboard', to: 'home#dashboard'
  get '/change_language/:locale', to: 'application#change_locale', as: :change_language
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  skip_before_action :require_login
  before_action :find_user, only: [:edit, :update]

  def new
  end

  def edit
  end

  def update
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.change_password!(params[:user][:password])
      client_info = ClientInfo.new(request.remote_ip, browser).serialize
      date_time = l Time.zone.now, format: :short
      UserMailer.new_password(@user, client_info, date_time).deliver_later
      redirect_to login_path, notice: t('reset_passwords.notices.password_changed')
    else
      render :edit
    end
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.activated? && user.approved?
      user.deliver_reset_password_instructions!
      redirect_to login_path, notice: t('reset_passwords.notices.password_sent')
    else
      flash.now[:error] = t 'reset_passwords.errors.wrong_email'
      render :new
    end
  end

  private

  def find_user
    @user = User.load_from_reset_password_token params[:id]
    return true if @user.present?
    redirect_to login_path, alert: t('reset_passwords.errors.wrong_token')
  end
end

app/views/reset_passwords/edit.html.slim
= extends :no_login do
  = simple_form_for @user, url: reset_password_path(params[:id]), wrapper: :admin_form do |f|
    .panel-body.bg-light.p30
      = f.input :password
      = f.input :password_confirmation

    .panel-footer.p25.pv15
      .row
        .col-md-12
          .section.mn
            = f.submit t('reset_passwords.buttons.submit'), class: 'btn btn-primary mr10 pull-right'

app/views/reset_passwords/new.html.slim
= extends :no_login do
  = form_tag reset_passwords_path do |f|
    .panel-body.bg-light.p30
      .alert.alert-micro.alert-border-left.alert-info.pastel.mn
        i.fa.fa-info.pr10
        = t 'reset_passwords.labels.instructions'

    .panel-footer.p25.pv15
      .row
        .col-md-12
          .section.mn
            .smart-widget.sm-right.smr-80
              label.field.prepend-icon
                = email_field_tag :email, params[:email], placeholder: t('sessions.placeholders.email'),
                                  required: true, class: 'gui-input'
                = label_tag :email, class: 'field-icon' do
                  i.fa.fa-envelope

              = button_tag t('reset_passwords.buttons.submit'), class: 'button btn-primary'