config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :sessions, only: [:new, :create]
  get 'login', controller: :sessions, action: :new
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'maintenance', to: 'sessions#maintenance', as: :maintenance

  resources :reset_passwords, except: [:index, :destroy, :show]
  get 'reset_password', controller: :reset_passwords, action: :new, as: :new_password

  resources :registrations, only: [:new, :create] do
    member do
      get 'activate'
    end
  end

  get 'dashboard', to: 'home#dashboard'
  get '/change_language/:locale', to: 'application#change_locale', as: :change_language
end

app/views/layouts/_flash_messages.html.slim
- flash.each do |key, value|
  - classes = flash_display_helper key
  .alert.alert-border-left.alert-dismissable class="alert-#{classes[:alert_class]}"
    button type='button' class='close' data-dismiss='alert' aria-hidden='true'
      | ×
    i.fa.pr10 class="fa-#{classes[:icon_class]}"
    = value

app/views/layouts/_left_sidebar.html.slim
= area :left_sidebar do
  aside#sidebar_left.nano.nano-primary
    .nano-content
      ul.nav.sidebar-menu
        li.sidebar-label.pt20= t 'menu.menu'
        li.active
          = link_to dashboard_path do
            span.glyphicons.glyphicons-home
            span.sidebar-title= t 'menu.dashboard'
        li
          = link_to logout_path do
            span.fa.fa-sign-out
            span.sidebar-title= t 'menu.logout'

app/views/layouts/_right_sidebar.html.slim
= area :right_sidebar do
  /! Start: Right Sidebar
  aside#sidebar_right.nano
    .sidebar_right_content.nano-content
      .tab-block.sidebar-block.br-n
        ul.nav.nav-tabs.tabs-border.nav-justified.hidden
          li.active
            a data-toggle="tab" href="#sidebar-right-tab1"  Tab 1
          li
            a data-toggle="tab" href="#sidebar-right-tab2"  Tab 2
          li
            a data-toggle="tab" href="#sidebar-right-tab3"  Tab 3
        .tab-content.br-n
          #sidebar-right-tab1.tab-pane.active
            h5.title-divider.text-muted.mb20
              | Server Statistics
              span.pull-right
                | 2013
                i.fa.fa-caret-down.ml5
            .progress.mh5
              .progress-bar.progress-bar-primary aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" style=("width: 44%")
                span.fs11 DB Request
            .progress.mh5
              .progress-bar.progress-bar-info aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" style=("width: 84%")
                span.fs11.text-left Server Load
            .progress.mh5
              .progress-bar.progress-bar-warning aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" style=("width: 61%")
                span.fs11.text-left Server Connections
            h5.title-divider.text-muted.mt30.mb10 Traffic Margins
            .row
              .col-xs-5
                h3.text-primary.mn.pl5 132
              .col-xs-7.text-right
                h3.text-success-dark.mn
                  i.fa.fa-caret-up
                  | 13.2%
            h5.title-divider.text-muted.mt25.mb10 Database Request
            .row
              .col-xs-5
                h3.text-primary.mn.pl5 212
              .col-xs-7.text-right
                h3.text-success-dark.mn
                  i.fa.fa-caret-up
                  | 25.6%
            h5.title-divider.text-muted.mt25.mb10 Server Response
            .row
              .col-xs-5
                h3.text-primary.mn.pl5 82.5
              .col-xs-7.text-right
                h3.text-danger.mn
                  i.fa.fa-caret-down
                  | 17.9%
            h5.title-divider.text-muted.mt40.mb20
              | Server Statistics
              span.pull-right.text-primary.fw600 USA
            #sidebar-right-map.hide-jzoom style=("width: 100%; height: 180px;")
          #sidebar-right-tab2.tab-pane
          #sidebar-right-tab3.tab-pane
            /! end: .tab-content
  /! End: Right Sidebar

app/views/layouts/_top_navbar.html.slim
= area :top_navbar do
  header.navbar.navbar-fixed-top.bg-light
    .navbar-branding
      = link_to dashboard_path, class: 'navbar-brand' do
        .pt3
          = image_tag 'logo_168x50px.png', alt: 'Virt.io Logo'

      span id='toggle_sidemenu_l' class='glyphicons glyphicons-show_lines'
        ul class='nav navbar-nav pull-right hidden'
          li
            a href='#' class='sidebar-menu-toggle'
              span class='octicon octicon-ruby fs20 mr10 pull-right'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'

    title= Settings.app.name

    meta name='keywords' content=Settings.app.keywords
    meta name='description' content=Settings.app.description
    meta name='author' content=Settings.company.name
    meta name='viewport' content='width=device-width, initial-scale=1.0'

    link rel='stylesheet' type='text/css' href='//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800'
    link rel="stylesheet" type="text/css" href='//fonts.googleapis.com/css?family=Roboto:400,500,700,300'

    link rel='icon' type='image/png' href='/icon_195px.png'
    link rel='apple-touch-icon-precomposed' href='/icon_72px.png'
    link rel='icon' type='image/png' href='/icon_16px.png'

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags

    /[if lt IE 9]
      = javascript_include_tag 'compatibility/html5shiv.js'
      = javascript_include_tag 'compatibility/respond.min.js'

  body class="#{yield :body_class}"
    #main
      = render 'layouts/top_navbar'
      = render 'layouts/left_sidebar'

      section#content_wrapper
        #content
          = render 'layouts/flash_messages'

          = yield

      = render 'layouts/right_sidebar'

  = javascript_include_tag 'theme/utility/utility'
  = javascript_include_tag 'theme/main'

app/views/layouts/no_login.html.slim
- content_for :body_class, 'external-page sb-l-c sb-r-c'

- replace :top_navbar, nil
- replace :left_sidebar, nil
- replace :right_sidebar, nil

.admin-form.theme-info
  .panel.panel-virtio.mt10.br-n
    .panel-heading.heading-border.bg-white
      .section.row.mn
        .col-sm-12
          = image_tag 'logo_392x110px.png', alt: 'Logo', class: 'img-responsive center-block'

    = yield

  .row.mbb15.table-layout
    .col-xs-6.va-m.pln
      = area :links do
        strong= link_to t('sessions.buttons.back'), login_path
    .col-xs-6.va-m.pln
      strong= locale_link

app/views/layouts/user_mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Oxygen Ping</title>

  <style type="text/css">
      /* Take care of image borders and formatting, client hacks */
      img {
          max-width: 600px;
          outline: none;
          text-decoration: none;
          -ms-interpolation-mode: bicubic;
      }

      a img {
          border: none;
      }

      table {
          border-collapse: collapse !important;
      }

      #outlook a {
          padding: 0;
      }

      .ReadMsgBody {
          width: 100%;
      }

      .ExternalClass {
          width: 100%;
      }

      .backgroundTable {
          margin: 0 auto;
          padding: 0;
          width: 100% !important;
      }

      table td {
          border-collapse: collapse;
      }

      .ExternalClass * {
          line-height: 115%;
      }

      .container-for-gmail-android {
          min-width: 600px;
      }

      /* General styling */
      * {
          font-family: Helvetica, Arial, sans-serif;
      }

      body {
          -webkit-font-smoothing: antialiased;
          -webkit-text-size-adjust: none;
          width: 100% !important;
          margin: 0 !important;
          height: 100%;
          color: #676767;
      }

      td {
          font-family: Helvetica, Arial, sans-serif;
          font-size: 14px;
          color: #777777;
          text-align: center;
          line-height: 21px;
      }

      a {
          color: #676767;
          text-decoration: none !important;
      }

      .pull-left {
          text-align: left;
      }

      .pull-right {
          text-align: right;
      }

      .header-lg,
      .header-md,
      .header-sm {
          font-size: 32px;
          font-weight: 700;
          line-height: normal;
          padding: 35px 0 0;
          color: #4d4d4d;
      }

      .header-md {
          font-size: 24px;
      }

      .header-sm {
          padding: 5px 0;
          font-size: 18px;
          line-height: 1.3;
      }

      .content-padding {
          padding: 20px 0 30px;
      }

      .mobile-header-padding-right {
          width: 290px;
          text-align: right;
          padding-left: 10px;
      }

      .mobile-header-padding-left {
          width: 290px;
          text-align: left;
          padding-left: 10px;
          padding-bottom: 8px;
      }

      .free-text {
          width: 100% !important;
          padding: 10px 60px 0px;
      }

      .block-rounded {
          border-radius: 5px;
          border: 1px solid #e5e5e5;
          vertical-align: top;
      }

      .button {
          padding: 30px 0;
      }

      .mini-block {
          border: 1px solid #e5e5e5;
          border-radius: 5px;
          background-color: #ffffff;
          padding: 12px 15px 15px;
          text-align: left;
          width: 253px;
      }

      .info-block {
          padding: 0 20px;
          width: 260px;
      }

      .block-rounded {
          width: 260px;
      }

      .info-img {
          width: 258px;
          border-radius: 5px 5px 0 0;
      }

      .force-width-img {
          width: 480px;
          height: 1px !important;
      }

      .force-width-full {
          width: 600px;
          height: 1px !important;
      }

      .force-width-gmail {
          min-width: 600px;
          height: 0px !important;
          line-height: 1px !important;
          font-size: 1px !important;
      }

      .button-width {
          width: 228px;
      }

  </style>

  <style type="text/css" media="screen">
      @import url(http://fonts.googleapis.com/css?family=Oxygen:400,700);
  </style>

  <style type="text/css" media="screen">
      @media screen {
          /* Thanks Outlook 2013! http://goo.gl/XLxpyl */
          * {
              font-family: 'Oxygen', 'Helvetica Neue', 'Arial', 'sans-serif' !important;
          }
      }
  </style>

  <style type="text/css" media="only screen and (max-width: 480px)">
      /* Mobile styles */
      @media only screen and (max-width: 480px) {

          table[class*="container-for-gmail-android"] {
              min-width: 290px !important;
              width: 100% !important;
          }

          table[class="w320"] {
              width: 320px !important;
          }

          img[class="force-width-gmail"] {
              display: none !important;
              width: 0 !important;
              height: 0 !important;
          }

          a[class="button-width"],
          a[class="button-mobile"] {
              width: 248px !important;
          }

          td[class*="mobile-header-padding-left"] {
              width: 160px !important;
              padding-left: 0 !important;
          }

          td[class*="mobile-header-padding-right"] {
              width: 160px !important;
              padding-right: 0 !important;
          }

          td[class="header-lg"] {
              font-size: 24px !important;
              padding-bottom: 5px !important;
          }

          td[class="header-md"] {
              font-size: 18px !important;
              padding-bottom: 5px !important;
          }

          td[class="content-padding"] {
              padding: 5px 0 30px !important;
          }

          td[class="button"] {
              padding: 5px !important;
          }

          td[class*="free-text"] {
              padding: 10px 18px 30px !important;
          }

          img[class="force-width-img"],
          img[class="force-width-full"] {
              display: none !important;
          }

          td[class="info-block"] {
              display: block !important;
              width: 280px !important;
              padding-bottom: 40px !important;
          }

          td[class="info-img"],
          img[class="info-img"] {
              width: 278px !important;
          }
      }
  </style>
</head>

<body bgcolor="#f7f7f7">
<table align="center" cellpadding="0" cellspacing="0" class="container-for-gmail-android" width="100%">
  <tr>
    <td align="left" valign="top" width="100%" style="background:repeat-x url(<%= asset_url('theme/emails/bg_top_02.jpg') %>) #ffffff;">
      <center>
        <img src="<%= asset_url('theme/emails/transparent.png') %>" class="force-width-gmail">
        <table cellspacing="0" cellpadding="0" width="100%" bgcolor="#ffffff" background="<%= asset_url('theme/emails/bg_top_02.jpg') %>" style="background-color:transparent">
          <tr>
            <td width="100%" height="80" valign="top" style="text-align: center; vertical-align:middle;">
              <!--[if gte mso 9]>
              <v:rect xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false"
                      style="mso-width-percent:1000;height:80px; v-text-anchor:middle;">
                  <v:fill type="tile" src="<%= asset_url('theme/emails/bg_top_02.jpg') %>"
                          color="#ffffff"/>
                  <v:textbox inset="0,0,0,0">
              <![endif]-->
              <center>
                <table cellpadding="0" cellspacing="0" width="600" class="w320">
                  <tr>
                    <td class="pull-left mobile-header-padding-left" style="vertical-align: middle;">
                      <a href="<%= Settings.company.web %>"><img width="168" height="50" src="<%= asset_url 'logo_168x50px.png' %>" alt="logo"></a>
                    </td>
                    <td class="pull-right mobile-header-padding-right" style="color: #4d4d4d;">
                      <a href="<%= t('links.social.twitter') %>">
                        <img width="40" height="47" src="<%= asset_url 'theme/emails/social-twitter.png' %>" alt="facebook"/>
                      </a>

                      <a href="<%= t('links.social.facebook') %>">
                        <img width="40" height="47" src="<%= asset_url 'theme/emails/social-fb.png' %>" alt="twitter"/>
                      </a>

                      <a href="<%= t('links.social.google_plus') %>">
                        <img width="32" height="32" src="<%= asset_url 'theme/emails/social-google.png' %>" alt="google plus"
                             style="padding-bottom: 7px" />
                      </a>

                      <!--<a href=""><img width="40" height="47" src="<%= asset_url 'theme/emails/social-feed.png' %>" alt="rss"/></a>-->
                    </td>
                  </tr>
                </table>
              </center>
              <!--[if gte mso 9]>
              </v:textbox>
              </v:rect>
              <![endif]-->
            </td>
          </tr>
        </table>
      </center>
    </td>
  </tr>
  <tr>
    <td align="center" valign="top" width="100%" style="background-color: #f7f7f7;" class="content-padding">
      <center>
        <table cellspacing="0" cellpadding="0" width="600" class="w320">
          <%= yield %>
        </table>
      </center>
    </td>
  </tr>

  <td align="center" valign="top" width="100%" style="background-color: #ffffff;  border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5;">
    <center>
      <table cellspacing="0" cellpadding="0" width="600" class="w320">
        <tr>
          <td style="padding: 25px 0 25px">
            <strong><%= Settings.company.name %></strong><br/>
            <%= mail_to Settings.company.email %> <br/>
            <%= link_to Settings.company.web, Settings.company.web %><br/>
            <%= Settings.company.phone %><br/>
          </td>
        </tr>
      </table>
    </center>
  </td>
</table>
</body>
</html>